# Generated by Django 5.2.12 on 2026-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AddField(
            model_name='mobilemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='phones/'),
        ),
    ]
